version: 2
jobs:
  deploy_staging:
    docker:
      - image: circleci/golang:1.11
        environment:
          DATABASE_CONNECTION_STRING: postgres://postgres:password@localhost:5432/crashtested_integrationtests?sslmode=disable
          APP_ENVIRONMENT: circleci
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: crashtested_integrationtests
    steps:
      - checkout
      - run: sudo apt-get -y -qq install awscli python-pip
      - run: pip install awsebcli --upgrade --user
      - run: echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
      - run: source ~/.bashrc
      - run: chmod +x ./deploy/setup_aws_credentials.sh && ./deploy/setup_aws_credentials.sh
      - run: sed -i "s/{LOCAL-DEV-BUILD}/${CIRCLE_BUILD_NUM}/g" ./cmd/api/main.go
      - run: sed -i "s/{LOCAL-DEV-COMMIT}/${CIRCLE_SHA1}/g" ./cmd/api/main.go
      - run: sed -i "s/{LOCAL-DEV-BUILD}/${CIRCLE_BUILD_NUM}/g" ./cmd/worker/main.go
      - run: sed -i "s/{LOCAL-DEV-COMMIT}/${CIRCLE_SHA1}/g" ./cmd/worker/main.go
      - run: go build -o crashtested-api ./cmd/api
      - run: go build -o crashtested-worker ./cmd/worker
      - run: go test -v ./...
      - run: zip -r api-artifacts.zip crashtested-api ./api/Procfile ./persistence/migrations/
      - run: zip -r worker-artifacts.zip crashtested-worker ./worker/Procfile ./persistence/migrations/
      - run: cp api-artifacts.zip workspace/artifacts
      - run: cp worker-artifacts.zip workspace/artifacts
      - run: mv api-artifacts.zip artifacts.zip
      - run: eb deploy api-staging --label api-${CIRCLE_SHA1} --process --verbose
      - run: rm artifacts.zip && mv worker-artifacts.zip artifacts.zip
      - run: eb deploy worker-staging --label worker-${CIRCLE_SHA1} --process --verbose
      - run: mkdir -p workspace/artifacts
      - persist_to_workspace:
          root: workspace
          paths:
            - artifacts
      - store_artifacts:
          path: workspace/artifacts/api-artifacts.zip
      - store_artifacts:
          path: workspace/artifacts/worker-artifacts.zip
  promote_staging_to_prod:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: sudo apt-get -y -qq install awscli python-pip
      - run: pip install awsebcli --upgrade --user
      - run: echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
      - run: source ~/.bashrc
      - run: chmod +x ./deploy/setup_aws_credentials.sh && ./deploy/setup_aws_credentials.sh
      - run: cp workspace/artifacts/api-artifacts.zip .
      - run: cp workspace/artifacts/worker-artifacts.zip .
      - run: mv api-artifacts.zip artifacts.zip
      - run: eb deploy api-prod --label api-${CIRCLE_SHA1} --process --verbose
      - run: rm artifacts.zip && mv worker-artifacts.zip artifacts.zip
      - run: eb deploy worker-prod --label worker-${CIRCLE_SHA1} --process --verbose
workflows:
  version: 2
  promote_to_prod:
    jobs:
      - deploy_staging
      - hold:
          type: approval
          requires:
            - deploy_staging
      - promote_staging_to_prod:
          requires:
            - hold
