version: 2
jobs:
  deploy_staging:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/crashtested-backend
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gopkg.toml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo apt-get -y -qq install awscli python-pip
      - run: pip install awsebcli --upgrade --user
      - run: echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
      - run: curl -L -o /go/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
      - run: chmod +x /go/bin/dep
      - run: dep ensure
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "Gopkg.toml" }}
      - run: go build -o crashtested-api ./api
      - run: go test -v ./...
      - run: eb --version
  promote_staging_to_prod:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: sudo apt-get -y -qq install awscli
workflows:
  version: 2
  promote_to_prod:
    jobs:
      - deploy_staging
      - hold:
          type: approval
          requires:
            - deploy_staging
      - promote_staging_to_prod:
          requires:
            - hold
