
-- +migrate Up
create table manufacturers (
    id serial primary key,
    name text not null unique
);

insert into manufacturers (name) values
    ('3GO'),
    ('AFX'),
    ('Agrius'),
    ('AGV'),
    ('Airoh'),
    ('Akuma'),
    ('Allpro'),
    ('Alltop'),
    ('Answer'),
    ('Apex'),
    ('Aprilla'),
    ('Arai'),
    ('Arashi'),
    ('ARC'),
    ('Arctic Cat'),
    ('Axo'),
    ('B2'),
    ('BCS'),
    ('Bell'),
    ('Beltenick'),
    ('Bieffe'),
    ('BKS'),
    ('Black Armor'),
    ('Black Cat'),
    ('Black'),
    ('BMW'),
    ('Bo Cai'),
    ('Bombardier'),
    ('Box'),
    ('BRP'),
    ('Buell'),
    ('Caberg'),
    ('Capacetes'),
    ('Charles Owen'),
    ('CMS'),
    ('Conquer'),
    ('Cyber'),
    ('Dainese'),
    ('Design Headwear'),
    ('Ducati'),
    ('Duchinni'),
    ('ERG'),
    ('EVS'),
    ('EXL'),
    ('F8'),
    ('Fimez'),
    ('Finn-Tack'),
    ('First Line'),
    ('Fly'),
    ('Foshan Nanhai Jiujiang Jiadeshi'),
    ('Fox'),
    ('FR'),
    ('Frank Thomas'),
    ('Fulmer'),
    ('Fusion'),
    ('FXR'),
    ('G-Force'),
    ('G-Mac'),
    ('Galuppo'),
    ('Gao Jin'),
    ('Gatehouse'),
    ('GDR'),
    ('Givi'),
    ('GLX'),
    ('GMax'),
    ('Goodwood Horseboxes'),
    ('Grattan'),
    ('Grex'),
    ('GT2i'),
    ('Halfords'),
    ('Hanmi'),
    ('Harley-Davidson'),
    ('Hedtec'),
    ('Hehui'),
    ('Helcim'),
    ('Helmet Solutions'),
    ('Hi-Speed'),
    ('HJC'),
    ('HLD'),
    ('HM'),
    ('Honda'),
    ('Hong Jin'),
    ('Hong Kong Sports'),
    ('Icon'),
    ('Impact'),
    ('INK'),
    ('ISA'),
    ('J-Tech'),
    ('Jiangmen Pengcheng'),
    ('Joe Rocket'),
    ('JT'),
    ('Kabut'),
    ('Kabuto'),
    ('Kawasaki'),
    ('KBC'),
    ('KC'),
    ('Keentech'),
    ('Kido'),
    ('Kimpex'),
    ('Kin Yong Lung'),
    ('Klim'),
    ('Koden'),
    ('KTM'),
    ('Kwon Chen'),
    ('Kylin'),
    ('KYT'),
    ('Lazer'),
    ('LEM'),
    ('Levior'),
    ('LS2'),
    ('M2R'),
    ('Marushin'),
    ('Mavet'),
    ('MDS'),
    ('MHR'),
    ('MMG'),
    ('Moose'),
    ('MSR'),
    ('MT'),
    ('MY'),
    ('Nankai'),
    ('Nava'),
    ('Nexx'),
    ('Nikko'),
    ('Ningbo'),
    ('Nitro'),
    ('No Fear'),
    ('Nolan'),
    ('Nuvo'),
    ('NZI'),
    ('O''Neal'),
    ('Octane'),
    ('OGK'),
    ('OMP'),
    ('ONE'),
    ('OSBE'),
    ('Osbe'),
    ('Parkgate Equestrian'),
    ('Peltor'),
    ('PM'),
    ('PMD'),
    ('Polaris'),
    ('Powersport'),
    ('PPM'),
    ('Premier'),
    ('ProRider'),
    ('PT. Tara Citra Kusuma'),
    ('Pyrotect'),
    ('Qranc'),
    ('Queen Kwan'),
    ('RACELID'),
    ('Racequip'),
    ('RAW'),
    ('RCI'),
    ('Real'),
    ('RJay'),
    ('Rodia'),
    ('Roof'),
    ('ROUX'),
    ('RPM'),
    ('RRS'),
    ('RST'),
    ('Ruby'),
    ('RXA'),
    ('Sabelt'),
    ('Schroth'),
    ('Schuberth'),
    ('Scorpion'),
    ('Scott Sports'),
    ('Security'),
    ('Sedici'),
    ('Seven O Seven'),
    ('Shark'),
    ('Shengchao'),
    ('Shift'),
    ('SHIRO'),
    ('Shoei'),
    ('Shokan'),
    ('Shox'),
    ('Simpson'),
    ('SixSixOne'),
    ('Snell'),
    ('Soaring'),
    ('SOL'),
    ('Spada'),
    ('Sparco'),
    ('Sparx'),
    ('Specialized'),
    ('Speed & Strength'),
    ('Stand 21'),
    ('Starplast'),
    ('Stealth'),
    ('Stilo'),
    ('Strategic Sports'),
    ('Sunright'),
    ('Suomy'),
    ('Super Seer'),
    ('Syko'),
    ('T.E.S.H.'),
    ('Takachi'),
    ('TDC'),
    ('TEQ'),
    ('TESI'),
    ('THH'),
    ('Thor'),
    ('Tong Ho Hsing'),
    ('Top Gear'),
    ('TORQ'),
    ('Troy Lee Designs'),
    ('TRP'),
    ('TTY'),
    ('Tung Kuang I Light'),
    ('Turini'),
    ('Turn-One'),
    ('Typhoon'),
    ('Urban'),
    ('Uvex'),
    ('V2'),
    ('V-Can'),
    ('Vantage'),
    ('VCAN'),
    ('Vega'),
    ('Vemar'),
    ('Victory'),
    ('Vigor'),
    ('Viper'),
    ('VM'),
    ('VOSS'),
    ('VR1'),
    ('Wayloo'),
    ('Winex'),
    ('Wombat'),
    ('Woo-In'),
    ('WPS'),
    ('X-Lite'),
    ('Xiang He Azul'),
    ('Xing Gang'),
    ('Xpeed'),
    ('Yamaha'),
    ('YOHE'),
    ('YueQing Kylin'),
    ('Z1R'),
    ('Z''Spirit'),
    ('Zamp'),
    ('Zeronine'),
    ('Zeus'),
    ('Zhuhai Star'),
    ('ZOX');

-- +migrate Down
drop table manufacturers;
